language: python
python:
- "2.7"
install: python setup.py develop
#install: python setup.py develop; pip install webtest unittest2
script: python setup.py test
#script: python setup.py test
notifications:
  email: 
    - gregory.komissarov@gmail.com
  irc:
    channels: 
        - "irc.freenode.org#firebat"
    on_success: change
